[package]
name = "flappy_ferris"
version = "0.1.0"
authors = ["Yukinari Tani <yukinarit84@gmail.com>"]
edition = "2018"

[dependencies]
quicksilver = "0.3.16"
serde = { version = "1.0", features = ["derive"] }
